<form method="post" action="<?= $block->getFormAction() ?>">
    <!-- Add your form fields here -->
    <input type="text" name="field1" placeholder="First name"/>
    <input type="text" name="field2" placeholder="Last name"  style="margin-top:10px;"/>
    <input type="email" name="field3" placeholder="Email" style="margin-top:10px;"/>
    <button type="submit" style="margin-top:10px;">Submit</button>
</form>